xtensa/esp32s3: Support multiple PHY init data bin
apache/nuttx pull request #11157
Opened 2023-11-09 03:34 UTC by cwespressif

## Summary

- Support partition and OTA device
- Support multiple PHY init data bin

## Impact

## Testing

If `CONFIG_ESP32S3_PHY_INIT_DATA_IN_PARTITION` and `CONFIG_ESP32S3_SUPPORT_MULTIPLE_PHY_INIT_DATA` are enabled, PHY initialization data (PHY initialization data is used for RF calibration) will be loaded from a partition, make sure that PHY data partition is included (type: 'data', subtype: 'phy').

The corresponding PHY init data type can be automatically switched according to the country code, China's PHY init data bin is used by default, country code can be modified through the wapi command: `wapi country <ifname> <country code>`.

Successful execution of `wapi country <ifname> <country code>` in `esp32s3-devkit:wifi` with `CONFIG_ESP32S3_PHY_INIT_DATA_IN_PARTITION=y` and `CONFIG_ESP32S3_SUPPORT_MULTIPLE_PHY_INIT_DATA=y`

2023-11-09 11:11 UTC, tmedicci commented
I'm running some local testing. Please don't merge it yet.

2023-11-09 22:02 UTC, acassis approved these changes

2023-11-10 11:14 UTC, tmedicci approved these changes

2023-11-10 11:32 UTC, jerpelea requested changes
can you please add commit messages.

2023-11-10 18:54 UTC, acassis approved these changes

2023-11-10 18:55 UTC, merged