ramlog: Add CONFIG_RAMLOG_KEEPLOG option
apache/nuttx pull request #11388
Opened 2023-12-13 13:52 UTC by PetteriAimonen

## Summary

Adds a new config option to prevent reading `/dev/kmsg` from clearing the log buffer. This way the latest log messages can be read multiple times, until the log gets overwritten when buffer is filled up.

This matches the behavior of /dev/kmsg on Linux.

## Impact

Old behavior is retained by default. When `CONFIG_RAMLOG_KEEPLOG` is enabled, reading `/dev/kmsg` no longer clears the buffer.

## Testing

Tested on custom STM32F4 board by using cat to read & write /dev/kmsg.

2023-12-13 14:10 UTC, xiaoxiang781216 commented
@PetteriAimonen we also made a similar change recently, but a little bit flexible which support multiple readers. Could you review our change whether suitable your needs?

2023-12-13 14:15 UTC, acassis requested changes

2023-12-13 14:15 UTC, acassis commented on drivers/syslog/Kconfig
> +config RAMLOG_KEEPLOG
@PetteriAimonen please include this information in the Documentation/, maybe a separated section for RAMLOG at https://nuttx.apache.org/docs/latest/components/drivers/special/syslog.html will be nice!

2023-12-13 14:28 UTC, PetteriAimonen commented
@xiaoxiang781216 I'd be glad to review. But somehow I can't see that change in pull request queue nor in the master branch?

2023-12-13 14:53 UTC, xiaoxiang781216 commented
> @xiaoxiang781216 I'd be glad to review. But somehow I can't see that change in pull request queue nor in the master branch?

We are preparing the patch set, will be available soon.

2023-12-13 15:03 UTC, PetteriAimonen commented
@xiaoxiang781216 Ok, sounds good :) No hurry on my part, I'll use my implementation for now.

2023-12-14 05:24 UTC, xiaoxiang781216 commented
> @xiaoxiang781216 Ok, sounds good :) No hurry on my part, I'll use my implementation for now.

@PetteriAimonen here is the patch:
https://github.com/apache/nuttx/pull/11393

2023-12-14 07:27 UTC, closed without merging