Fix the compilation warnings
apache/nuttx pull request #13054
Opened 2024-08-20 07:30 UTC by liqinhuixm

## Summary
Fix the compilation warnings
## Impact
N/A
## Testing
N/A

2024-08-20 07:33 UTC, jerpelea approved these changes

2024-08-20 11:35 UTC, anchao requested changes

2024-08-20 11:35 UTC, anchao commented on drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
>    UNUSED(priv);
```suggestion
```

2024-08-20 11:35 UTC, anchao commented on drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
>    UNUSED(priv);
```suggestion
```

2024-08-21 02:41 UTC, liqinhuixm commented on drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
>    UNUSED(priv);
Done

2024-08-21 02:41 UTC, liqinhuixm commented on drivers/wireless/ieee80211/bcm43xxx/bcmf_netdev.c
>    UNUSED(priv);
Done

2024-08-21 10:00 UTC, anchao approved these changes

2024-08-21 15:30 UTC, xiaoxiang781216 approved these changes

2024-08-21 15:30 UTC, merged