tools/ci: Add more bindings apps for QEMU RISC-V.
apache/nuttx pull request #13139
Opened 2024-08-23 14:05 UTC by kassane

> could you create a new patch to enable hello_swift ci?
> 
>   * [**"Building the Docker Image for NuttX CI"**](https://lupyuen.github.io/articles/pr#appendix-building-the-docker-image-for-nuttx-ci)
> 
>  * [**"Downloading the Docker Image for NuttX CI"**](https://lupyuen.github.io/articles/pr#appendix-downloading-the-docker-image-for-nuttx-ci)

### Reviewers
cc: @lupyuen @xiaoxiang781216 

---

### Steps

Based on #12858, add another languages support on tool/ci.

- [ ] Zig v0.13.0 support (using zigup - version manager) *static-binary, running any distro.
- [ ] Swiftly support (like, rustup) - works in ubuntu 20.04, 22.04, but 24.04 (wip)
- [ ] ldc2 tarball (no version manager).

2024-08-23 14:25 UTC, acassis reviewed
Please include a commit message explaining the purpose of adding these new languages to CI

2024-08-23 14:56 UTC, kassane commented
> Please include a commit message explaining the purpose of adding these new languages to CI

The main objective is to determine if the examples really work or if they have been obsoleted.
The languages included in the list promote good interoperability with the NuttX API (C predominant).

It is possible that the examples of these languages will need to be improved to go beyond a simple "hello world!".
This will show if they are worth integrating in NuttX.

- Rust, which is currently gaining popularity for its secure language ("safe memory"), Swift is following the same trend (leaving Apple exclusivity).
- Zig and D meet the needs of a specific group of developers, pioneers, enthusiasts, or even professionals (embedded focused).

This PR will continue as a draft. It will test the languages mentioned above (except rust).
**The unnecessary will be discarded in the final solution.**

2024-08-23 15:07 UTC, acassis commented
@kassane understood. Please include this info to the commit message (using git commit --amend or git rebase interactive) and push forced to update the PR

2024-08-25 14:44 UTC, xiaoxiang781216 commented
@kassane please squash to one patch

2024-08-25 18:36 UTC, acassis requested changes
Please include the commit log message

2024-08-25 18:40 UTC, acassis commented
@kassane you can put the information you wrote here in the commit log

2024-08-25 19:08 UTC, kassane commented
> @kassane you can put the information you wrote here in the commit log

@acassis,

I'll do it! However, before concluding, I'm waiting for the review of the examples.

- https://github.com/apache/nuttx-apps/pull/2534 (need drop-off, any toolchain on CI? Useless or no??)

2024-08-25 19:33 UTC, acassis approved these changes

2024-08-26 00:31 UTC, lupyuen approved these changes
Thank you so much for adding D, Swift and Zig to NuttX CI!

2024-08-26 01:07 UTC, kassane commented
You're welcome!

If you have any questions, please let me know.

2024-08-26 02:25 UTC, xiaoxiang781216 approved these changes

2024-08-26 02:25 UTC, merged

2024-08-26 02:26 UTC, xiaoxiang781216 commented
it's time to enable language examples in some qemu/sim configuration, @kassane

2024-08-26 06:40 UTC, lupyuen commented
@xiaoxiang781216 Sorry what does this error mean for the ` Docker-Linux` build? Are we out of disk space for the Docker Image? Thanks! https://github.com/apache/nuttx/actions/runs/10552464652/job/29236244423

```text
97 [stage-12 53/53] RUN mkdir -p /tools/ccache/bin &&   ln -sf `which ccache` /tools/ccache/bin/aarch64-none-elf-gcc &&   ln -sf `which ccache` /tools/ccache/bin/aarch64-none-elf-g++ &&   ln -sf `which ccache` /tools/ccache/bin/arm-none-eabi-gcc &&   ln -sf `which ccache` /tools/ccache/bin/arm-none-eabi-g++ &&   ln -sf `which ccache` /tools/ccache/bin/avr-gcc &&   ln -sf `which ccache` /tools/ccache/bin/avr-g++ &&   ln -sf `which ccache` /tools/ccache/bin/avr32-gcc &&   ln -sf `which ccache` /tools/ccache/bin/avr32-g++ &&   ln -sf `which ccache` /tools/ccache/bin/cc &&   ln -sf `which ccache` /tools/ccache/bin/c++ &&   ln -sf `which ccache` /tools/ccache/bin/clang &&   ln -sf `which ccache` /tools/ccache/bin/clang++ &&   ln -sf `which ccache` /tools/ccache/bin/gcc &&   ln -sf `which ccache` /tools/ccache/bin/g++ &&   ln -sf `which ccache` /tools/ccache/bin/p32-gcc &&   ln -sf `which ccache` /tools/ccache/bin/rx-elf-gcc &&   ln -sf `which ccache` /tools/ccache/bin/riscv-none-elf-gcc &&   ln -sf `which ccache`
#97 DONE 0.1s
#98 exporting to image
#98 exporting layers
#98 exporting layers 108.4s done
#98 ERROR: mount callback failed on /tmp/containerd-mount1340964273: mount callback failed on /tmp/containerd-mount2504404974: failed to write compressed diff: failed to create diff tar stream: failed to copy: write /var/lib/buildkit/runc-overlayfs/content/ingest/1e55b0e585604cd155a508fc2b84febb206d7fc2e8b0a5c2c8bcbeb296b952f7/data: no space left on device
```

2024-08-26 13:33 UTC, kassane commented
> it's time to enable language examples in some qemu/sim configuration

Sorry timezone delay! I do.

2024-08-26 15:48 UTC, xiaoxiang781216 commented
> @xiaoxiang781216 Sorry what does this error mean for the ` Docker-Linux` build? Are we out of disk space for the Docker Image? Thanks! https://github.com/apache/nuttx/actions/runs/10552464652/job/29236244423
> 
> ```
> 97 [stage-12 53/53] RUN mkdir -p /tools/ccache/bin &&   ln -sf `which ccache` /tools/ccache/bin/aarch64-none-elf-gcc &&   ln -sf `which ccache` /tools/ccache/bin/aarch64-none-elf-g++ &&   ln -sf `which ccache` /tools/ccache/bin/arm-none-eabi-gcc &&   ln -sf `which ccache` /tools/ccache/bin/arm-none-eabi-g++ &&   ln -sf `which ccache` /tools/ccache/bin/avr-gcc &&   ln -sf `which ccache` /tools/ccache/bin/avr-g++ &&   ln -sf `which ccache` /tools/ccache/bin/avr32-gcc &&   ln -sf `which ccache` /tools/ccache/bin/avr32-g++ &&   ln -sf `which ccache` /tools/ccache/bin/cc &&   ln -sf `which ccache` /tools/ccache/bin/c++ &&   ln -sf `which ccache` /tools/ccache/bin/clang &&   ln -sf `which ccache` /tools/ccache/bin/clang++ &&   ln -sf `which ccache` /tools/ccache/bin/gcc &&   ln -sf `which ccache` /tools/ccache/bin/g++ &&   ln -sf `which ccache` /tools/ccache/bin/p32-gcc &&   ln -sf `which ccache` /tools/ccache/bin/rx-elf-gcc &&   ln -sf `which ccache` /tools/ccache/bin/riscv-none-elf-gcc &&   ln -sf `which ccache`
> #97 DONE 0.1s
> #98 exporting to image
> #98 exporting layers
> #98 exporting layers 108.4s done
> #98 ERROR: mount callback failed on /tmp/containerd-mount1340964273: mount callback failed on /tmp/containerd-mount2504404974: failed to write compressed diff: failed to create diff tar stream: failed to copy: write /var/lib/buildkit/runc-overlayfs/content/ingest/1e55b0e585604cd155a508fc2b84febb206d7fc2e8b0a5c2c8bcbeb296b952f7/data: no space left on device
> ```

Yes, @btashton @simbit18 do you have any suggestion to reduce docker image size?

2024-08-26 16:42 UTC, simbit18 commented
@xiaoxiang781216  Yes, it appears so.

You need to see the current plan
https://github.com/settings/billing/summary

Old caches must also be removed
https://github.com/apache/nuttx/actions/caches