Pci ep framework
apache/nuttx pull request #13553
Opened 2024-09-20 07:41 UTC by lipengfei28

## Summary
nuttx add pci ep framework
## Impact

## Testing

2024-09-20 07:49 UTC, nuttxpr commented
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)

__Squash The Commits:__ This PR contains 6 Commits. Please Squash the Multiple Commits into a Single Commit.



**No, this PR does not meet the NuttX requirements.**

**Summary:**

* **Insufficient information:** The summary is too brief and lacks essential details. It doesn't explain:
    * **Necessity:** Why is the PCI EP framework needed? What problem does it solve, or what improvement does it bring?
    * **Functionality:** Which part of the codebase is affected? What specific PCI EP capabilities are being added?
    * **Implementation:** How does the framework work? What changes have been made to the code?
* **Missing references:**  Are there related NuttX issues or NuttX Apps issues/pull requests?

**Impact:**

* **Entirely missing:** The impact section is empty.  You must address all the points to demonstrate a thorough understanding of your changes.

**Testing:**

* **No details provided:** 
    *  You need to list the specific build hosts (OS, CPU, compiler) and target devices (architecture, board, configuration) where you tested the changes.
    *  Provide actual testing logs from **before** and **after** the change to show the difference in behavior.

**To improve this PR:**

1. **Expand the Summary:** Provide a clear and detailed explanation of the changes, their purpose, and how they are implemented.
2. **Complete the Impact section:** Analyze and describe the impact of your changes on all the listed aspects (user, build, hardware, documentation, security, compatibility).
3. **Provide Testing Details:** Specify your build hosts and target devices, and include relevant testing logs from before and after applying your changes.

**By addressing these points, your PR will be far more likely to be reviewed and merged.**

2024-09-20 10:28 UTC, jerpelea requested changes
please fill commit messages explaining the changes

2024-09-23 02:47 UTC, lipengfei28 commented
@jerpelea  I add the comment and explain the change

2024-09-23 04:49 UTC, xiaoxiang781216 approved these changes

2024-09-23 08:03 UTC, merged