mqueue: revert refactor of mqueue
apache/nuttx pull request #13814
Opened 2024-10-03 16:09 UTC by fdcavalcanti

## Summary
This PR reverts #13413 which refactors mqueue.
The reason for this is that this refactor broke the WiFi CI on both Xtensa and RISC-V Espressif devices.

So far, the following has stopped working across affected SoCs:
- `ifconfig` after reboot not responding as it used to
- connection to AP using `wapi` throws many errors and is unstable
- Multiple failures on WiFi performance test using IPERF.

If this affected Espressif devices using those tools, it is possible it affected other devices as well. I'm keeping an eye open on new issues.

## Impact
Restores WiFi support on Espressif devices.

## Testing
Reverted #13413 on master, run the entire CI and everything works again.

2024-10-03 22:28 UTC, lupyuen approved these changes

2024-10-04 02:06 UTC, GUIDINGLI commented
Hold for some time, and I will give you a different way to handle this issue.

2024-10-04 02:32 UTC, GUIDINGLI commented
@fdcavalcanti 
Please, provide how to build, how to execute the bin, how to reproduce the issue.

2024-10-04 02:44 UTC, GUIDINGLI requested changes
You must give a Qemu reproduce ENV for this issue

2024-10-04 11:52 UTC, fdcavalcanti commented
Hi @GUIDINGLI. I'll check if QEMU can reproduce this.

Meanwhile, a quick way of viewing the errors:
- Build setup: `./tools/configure.sh esp32-devkitc:sta_softap`
- Set CONFIG_DEBUG_FEATURES, CONFIG_DEBUG_NET, CONFIG_DEBUG_NET_ERROR, CONFIG_DEBUG_NET_WARN, CONFIG_DEBUG_WIRELESS, CONFIG_DEBUG_WIRELESS_ERROR, CONFIG_DEBUG_WIRELESS_WARN
- Build and flash.

Run `wapi scan wlan0` a couple of times and it stops responding.

2024-10-04 11:53 UTC, fdcavalcanti commented
> Hold for some time, and I will give you a different way to handle this issue.

What's your plan here?

2024-10-05 14:21 UTC, GUIDINGLI commented
> > Hold for some time, and I will give you a different way to handle this issue.
> 
> What's your plan here?

Sorry, don't have esp32 env current now.
Can reproduce on Qemu? If so, that will be very helpful for this issue

2024-10-06 07:19 UTC, GUIDINGLI commented
@fdcavalcanti 

Please see:
https://github.com/apache/nuttx/pull/13841

The rootcause is not mq's refactor, but there already has a bug on esp32 time calculation.
One suggestion, if you meet a question, try to fix the bug first time.

2024-10-06 07:20 UTC, GUIDINGLI commented
@fdcavalcanti 
You can close this PR now.

2024-10-06 07:33 UTC, closed without merging

2024-10-07 11:53 UTC, fdcavalcanti commented
@GUIDINGLI thank you for the fix.
I hope you did not take this personally. Sorry about the confusion around this issue.

2024-10-07 17:00 UTC, fdcavalcanti commented
Please let's stand by on this. 
Don't know what gave the impression that PR should be merged but the proposed fix did not work and we have WiFi still failing across all devices. Still looking into it.

2024-10-08 02:59 UTC, xiaoxiang781216 commented
> @GUIDINGLI thank you for the fix. 

Sorry, from this reply, I think you verify that https://github.com/apache/nuttx/pull/13841 fix your problem.