pthread_cond remove csection  and sched_lock
apache/nuttx pull request #14581
Opened 2024-10-31 12:43 UTC by hujun260

## Summary
We decouple semcount from business logic by using an independent counting variable, which allows us to remove critical sections in many cases.

## Impact
pthread_cond

## Testing
ci ostest

**Build Host:**
* OS: Ubuntu 20.04
* CPU: x86_64 
* Compiler: GCC 9.4.0

Configuring NuttX and compile:
$ ./tools/configure.sh -l qemu-armv8a:nsh_smp
$ make
Running with qemu
$ qemu-system-aarch64 -cpu cortex-a53 -smp 4 -nographic \
   -machine virt,virtualization=on,gic-version=3 \
   -net none -chardev stdio,id=con,mux=on -serial chardev:con \
   -mon chardev=con,mode=readline -kernel ./nuttx

2024-10-31 13:09 UTC, acassis approved these changes

2024-10-31 13:09 UTC, acassis commented
Good idea @hujun260 !!!

2024-11-01 00:29 UTC, anchao requested changes

2024-11-01 00:29 UTC, anchao commented on sched/pthread/pthread_condclockwait.c
> +      cond->lock_count--;
remove the comments from line 116 to 120

2024-11-01 05:27 UTC, anchao approved these changes

2024-11-01 07:04 UTC, jerpelea approved these changes

2024-11-02 12:40 UTC, merged

2024-11-14 01:04 UTC, xiaoxiang781216 commented on include/pthread.h
> +  volatile int16_t lock_count;
wait_count and remove volatile. should we change to atomic type

2024-11-14 01:04 UTC, xiaoxiang781216 commented on sched/pthread/pthread_condclockwait.c
> +      cond->lock_count--;
wait_count++

2024-11-14 01:04 UTC, xiaoxiang781216 commented on sched/pthread/pthread_condsignal.c
> +      if (cond->lock_count < 0)
cond->wait_count > 0

2024-11-14 01:04 UTC, xiaoxiang781216 commented on sched/pthread/pthread_condsignal.c
> -  int sval;
where we change pthread_cond_broadcast