Feature/esp spi bitbang
apache/nuttx pull request #14590
Opened 2024-11-01 08:38 UTC by eren-terzioglu

*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*

## Summary

*Update this section with information on why change is necessary,
 what it exactly does and how, if new feature shows up, provide
 references (dependencies, similar problems and solutions), etc.*

## Impact

*Update this section, where applicable, on how change affects users,
 build process, hardware, documentation, security, compatibility, etc.*

## Testing

*Update this section with details on how did you verify the change,
 what Host was used for build (OS, CPU, compiler, ..), what Target was
 used for verification (arch, board:config, ..), etc. Providing build
 and runtime logs from before and after change is highly appreciated.*

2024-11-01 11:43 UTC, tmedicci commented on arch/risc-v/src/common/espressif/esp_spi_bitbang.c
> +#endif /* CONFIG_ESPRESSIF_SPI_BITBANG */
Missing new line?

2024-11-01 11:43 UTC, tmedicci commented on arch/risc-v/src/common/espressif/esp_spi_bitbang.c
> +#endif /* CONFIG_ESPRESSIF_SPI_BITBANG */
Can you double-check other occurrences?

2024-11-01 14:25 UTC, acassis approved these changes

2024-11-01 16:13 UTC, xiaoxiang781216 approved these changes

2024-11-01 16:14 UTC, xiaoxiang781216 commented
please fix the conflict, @eren-terzioglu

2024-11-01 17:32 UTC, eren-terzioglu commented
> please fix the conflict, @eren-terzioglu

Thanks for informing, updated.

2024-11-04 13:43 UTC, acassis commented
@lupyuen do you have some idea about this error:

```
+ python3 -m pytest -m 'common or sim' ./ -B sim -P -L /github/workspace/sources/nuttx/boards/sim/sim/sim/configs/citest/logs/sim/sim -R sim -C --json=/github/workspace/sources/nuttx/boards/sim/sim/sim/configs/citest/logs/sim/sim/pytest.json
/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py:318: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
UsageError: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: argument -P: expected one argument
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: argument -P: expected one argument
```

2024-11-06 05:16 UTC, lupyuen requested changes

2024-11-06 05:16 UTC, lupyuen commented on arch/xtensa/src/common/espressif/Kconfig
> +>>>>>>> esp32[s2|s3]: Add SPI bitbang support
And this merge too thanks!

2024-11-06 05:16 UTC, lupyuen commented on arch/xtensa/src/common/espressif/Kconfig
> +<<<<<<< HEAD
Could you fix this merge?

2024-11-06 07:58 UTC, eren-terzioglu commented
Thanks @lupyuen, updated

2024-11-06 08:00 UTC, lupyuen approved these changes

2024-11-06 09:52 UTC, eren-terzioglu commented
Seems [error](https://github.com/apache/nuttx/actions/runs/11699400503/job/32581383483?pr=14590#step:7:364) is unrelated to this PR, we can fix it in other PR.

2024-11-06 09:59 UTC, lupyuen commented
@eren-terzioglu Yep let's wait for the Red Error Boxes below to disappear from nuttx-dashboard.org. Then we can [rebase with master](https://lupyuen.github.io/articles/pr#submit-the-pull-request).

Meanwhile I cloned your fork to [my repo](https://github.com/nuttxpr2/nuttx/tree/feature/esp_spi_bitbang), enabled [all the builds](https://github.com/nuttxpr2/nuttx/commit/9e4aab7f0326f396b26cb6d9218c076c353d82e3), to check if there are other errors: https://github.com/nuttxpr2/nuttx/actions/runs/11701148540

![Screenshot 2024-11-06 at 5 55 03 PM](https://github.com/user-attachments/assets/eec9f3b4-7a65-4366-b2ce-395105137aaa)

2024-11-06 10:01 UTC, xiaoxiang781216 approved these changes

2024-11-06 11:47 UTC, merged