armv8-m/cortex-m85: add support of PACBTI(Authentication and Branch Target Identification Extension)
apache/nuttx pull request #8747
Opened 2023-03-06 15:06 UTC by anchao

## Summary

armv8-m/cortex-m85: add support of PACBTI(Authentication and Branch Target Identification Extension)

Reference:
https://developer.arm.com/documentation/100748/0617/Security-features-supported-in-Arm-Compiler-for-Embedded/PACBTI-M-extension-mitigations-against-ROP-and-JOP-style-attacks

Signed-off-by: chao an <anchao@xiaomi.com>

## Impact

N/A

## Testing

ci-check

2023-03-06 15:24 UTC, pkarashchenko approved these changes

2023-03-06 15:46 UTC, xiaoxiang781216 approved these changes

2023-03-06 17:09 UTC, xiaoxiang781216 requested changes

2023-03-06 17:09 UTC, xiaoxiang781216 commented on arch/arm/src/armv8-m/Toolchain.defs
> +ifeq ($(CONFIG_ARM_HAVE_PACBTI),y)
```suggestion
ifeq ($(CONFIG_ARM_PACBTI),y)
```

2023-03-07 03:07 UTC, anchao commented on arch/arm/src/armv8-m/Toolchain.defs
> +ifeq ($(CONFIG_ARM_HAVE_PACBTI),y)
Done

2023-03-07 03:12 UTC, xiaoxiang781216 approved these changes

2023-03-07 03:14 UTC, xiaoxiang781216 approved these changes

2023-03-07 05:34 UTC, merged