boards/stm32: add composite device configurations
apache/nuttx pull request #8952
Opened 2023-04-03 14:21 UTC by raiden00pl

## Summary

- stm32f4discovery: add composite device configuration
- stm32f4discovery/stm32_usbmsc.c: fix SD card initialization
- stm32f4discovery/stm32_mmcsd.c: remove redundant SCK pin configuration, it's already selected in board.h
- nucleo-144: add composite device configuration
- nucleo-h743zi: add composite device configuration

## Impact

## Testing
Added configuration

2023-04-04 15:56 UTC, davids5 commented
@raiden00pl Did you rest this on the all the effected HW?

2023-04-04 16:16 UTC, raiden00pl commented
Yes, they were all tested. They are based on the same IP core (dwc2 from Synopsys) and I hoped that one stm32 would work as a composite device. Unfortunately, the main problems were in USB drivers but at least some new configs were created.

2023-04-04 16:17 UTC, davids5 approved these changes
Thank you @raiden00pl

2023-04-04 17:37 UTC, pkarashchenko approved these changes
Nothing that blocks from merging

2023-04-04 17:37 UTC, pkarashchenko commented on boards/arm/stm32h7/nucleo-h743zi/src/stm32_composite.c
> +  dev_idx += 1;
Nitpick:

```suggestion
  dev_idx++;
```

2023-04-04 17:37 UTC, pkarashchenko commented on boards/arm/stm32h7/nucleo-h743zi/src/stm32_composite.c
> +  dev_idx += 1;
```suggestion
  dev_idx++;
```

2023-04-04 17:37 UTC, pkarashchenko commented on boards/arm/stm32h7/nucleo-h743zi/src/stm32_composite.c
> +  dev_idx += 1;
```suggestion
  dev_idx++;
```

2023-04-21 17:48 UTC, xiaoxiang781216 commented
@raiden00pl please fix the conflict.

2023-05-03 12:17 UTC, raiden00pl commented
@xiaoxiang781216 conflict fixed

2023-05-03 13:28 UTC, pkarashchenko commented on boards/arm/stm32f7/nucleo-144/src/stm32_composite.c
> +  int strbase  = COMPOSITE_NSTRIDS;
```suggestion
  int strbase = COMPOSITE_NSTRIDS;
```

2023-05-03 13:28 UTC, pkarashchenko commented on boards/arm/stm32h7/nucleo-h743zi/src/stm32_composite.c
> +  int strbase  = COMPOSITE_NSTRIDS;
```suggestion
  int strbase = COMPOSITE_NSTRIDS;
```

2023-05-04 07:51 UTC, davids5 requested changes
@raiden00pl Looks good but some minor changes.

2023-05-04 07:51 UTC, davids5 commented on boards/arm/stm32h7/nucleo-h743zi/src/nucleo-h743zi.h
> +                           GPIO_OUTPUT_SET | GPIO_PORTD | GPIO_PIN15)
```suggestion
                          GPIO_OUTPUT_SET | GPIO_PORTD | GPIO_PIN15)
```

2023-05-04 12:31 UTC, xiaoxiang781216 commented
@raiden00pl will you fix the remaining comment from @pkarashchenko ?

2023-05-08 16:56 UTC, raiden00pl commented
@xiaoxiang781216  I prefer to keep the code as it is now.

2023-05-08 16:59 UTC, merged