SAMA5D2, improve LCD support and correct minor errors
apache/nuttx pull request #9390
Opened 2023-05-25 14:47 UTC by TimJTi

## Summary

1. Adds 2 missing modes that I needed (ARGB8888 and RGBA8888)
2. Additions needed for SAMA5D2 rather than SAMA5D3 originally used as the reference
3. Tidies the code
4. Does NOT (after all) replace licence agreement with the Apache variant, as there are BSD restrictions
5. Corrects print formatting

## Impact
None expected

## Testing
Custom board with ATSAMA5D27C-D1M with 800x480 TFT LCD

2023-05-25 18:17 UTC, mu578 commented
@TimJTi, in your previous draft you also had numerous typos in comment sections added.

2023-05-25 18:48 UTC, TimJTi commented
> @TimJTi, in your previous draft you also had numerous typos in comment sections added.

@mu578 - not caused by me! They will have been there from whoever did this driver originally. Since it is still failing CI checks  (for things I am trying to sort, since the file has not been worked on in year by anyone so has errors that cause it to fail now) I will try and find as many as I can. It passes checkpatch.sh however....grrrr.

2023-05-25 20:06 UTC, mu578 commented
@TimJTi I know but as you are already in editing copyright sections too, you did sign for it 8-D.

2023-05-26 14:07 UTC, btashton requested changes
@jerpelea I assume this file never had the license changed from BSD because it is based on some Atmel code? If that is correct the license header should be left in place.

2023-05-26 14:21 UTC, TimJTi commented
> @jerpelea I assume this file never had the license changed from BSD because it is based on some Atmel code? If that is correct the license header should be left in place.

I should have read the license that was there - my mistake. Trying to be too helpful lol. Reverted.

2023-05-26 14:23 UTC, btashton commented
> > @jerpelea I assume this file never had the license changed from BSD because it is based on some Atmel code? If that is correct the license header should be left in place.
> 
> I should have read the license that was there - my mistake. Trying to be too helpful lol. Reverted.

No worries, thanks for doing some cleanup here along with the fixes.

2023-05-26 19:21 UTC, xiaoxiang781216 commented on arch/arm/src/sama5/sam_lcd.c
> +  lcdinfo("Clearing display: BPP=32 color=%" PRIx32 \
remove \

2023-05-26 19:21 UTC, xiaoxiang781216 commented on arch/arm/src/sama5/sam_lcd.c
> +  lcdinfo("Clearing display: BPP=24 color=%" PRIx32 \
remove \

2023-05-26 19:21 UTC, xiaoxiang781216 commented on arch/arm/src/sama5/sam_lcd.c
> +  lcdinfo("DMA registers[%d]: head=%" PRIx32 " addr=%" PRIx32 " ctrl=%" \
remove \

2023-05-26 19:21 UTC, xiaoxiang781216 commented on arch/arm/src/sama5/sam_lcd.c
> +  lcdinfo("DMA descriptor:   addr=%" PRIx32 " ctrl=%" PRIx32 " next=%" \
```suggestion
  lcdinfo("DMA descriptor:   addr=%" PRIx32 " ctrl=%" PRIx32 " next=%"
```

2023-05-27 06:02 UTC, xiaoxiang781216 approved these changes

2023-05-27 06:03 UTC, merged

2023-05-29 11:14 UTC, jerpelea commented
> > @jerpelea I assume this file never had the license changed from BSD because it is based on some Atmel code? If that is correct the license header should be left in place.
> 
> I should have read the license that was there - my mistake. Trying to be too helpful lol. Reverted.

don't worry